# Holds DAP config info for apps in all namespaces
# Access is gained via rolebinding to a clusterrole
# Master and Follower certs are appended after template values instantiated.
apiVersion: v1
kind: ConfigMap
metadata:
  name: dap-config
data:
  CONJUR_ACCOUNT: lab
  CONJUR_MASTER_HOST_NAME: dap-service-node-cyberlab.apps.cluster-436d.436d.sandbox1159.opentlc.com
  CONJUR_MASTER_URL: https://dap-service-node-cyberlab.apps.cluster-436d.436d.sandbox1159.opentlc.com
  CLUSTER_AUTHN_ID: cyberlab
  CONJUR_VERSION: "5"
  CONJUR_APPLIANCE_URL: https://dap-service-node.cyberlab.svc.cluster.local
  CONJUR_AUTHN_URL: https://dap-service-node.cyberlab.svc.cluster.local/api/authn-k8s/cyberlab
  CONJUR_AUTHN_TOKEN_FILE: /run/conjur/access-token
  CONJUR_MASTER_CERTIFICATE: |
    -----BEGIN CERTIFICATE-----
    MIIDmTCCAoGgAwIBAgIVAPWJGXeq9H9m0gyd4YlXoSHJP1qnMA0GCSqGSIb3DQEB
    CwUAMFgxDDAKBgNVBAoMA2xhYjESMBAGA1UECwwJQ29uanVyIENBMTQwMgYDVQQD
    DCtkYXAtc2VydmljZS1ub2RlLmN5YmVybGFiLnN2Yy5jbHVzdGVyLmxvY2FsMB4X
    DTIxMTAyMDA5NTQ0MVoXDTMxMTAxODA5NTQ0MVowNjE0MDIGA1UEAwwrZGFwLXNl
    cnZpY2Utbm9kZS5jeWJlcmxhYi5zdmMuY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBAMrvwBCeuB/79O1tm7H678vhP2MtZAo/jLd6
    StVlzFxYQcyGEfSzqX+s6R+7e85hKdSyrPjuLc+c7IDv/RzrEwVVx1fClcZZlMR6
    xY3BX35UDaQpT9bDiAIRgCCBC0571U+u6vGiM0aaOdltEqIUHQfuMje1XM4b1KTv
    bT89iqnqBx9q4l5no69E2a5Opqqb3eRRr+Jrv6Zdt0e8JVXeVIBVGUWkpoftX1YU
    KrA0H0GNQ5qbAZjEbif92UfBETvi6kejTuqYnQlvlsnEIepZ5OUIi67DwOjeLKsD
    rsuhSgq4HAQdJFjBEt0OtJcYYhKLWvYSccfMvuVEN2/t7PrGC30CAwEAAaN8MHow
    DgYDVR0PAQH/BAQDAgWgMB0GA1UdDgQWBBTaOaPuXmtLDTJVv++VYBiQr9gHCTBJ
    BgNVHREEQjBAgitkYXAtc2VydmljZS1ub2RlLmN5YmVybGFiLnN2Yy5jbHVzdGVy
    LmxvY2Fsgglsb2NhbGhvc3SCBmNvbmp1cjANBgkqhkiG9w0BAQsFAAOCAQEA1vl7
    xE+UNiEcN+KuwOP0E120oQ2d22/BS/DE1smjFEqU+JhMN1bsBWRbi8Y+FhbCpkUr
    pqCr7FUW9HB04Sa0Yb/wyoG8F6EcUdPHInXiIv6nH6tiWER5zRVmVn4Ra86vLaA9
    58sBaPowWcRQRGy2FWNvDNiWmI1Z7UBxaL8lV35yKxzye8zbK+TQxtkONv/aNpUI
    Jz/Wg8HXcT3fegyAdKKTUBY1AVs6nsAEBNj10hyB2bj4+xNtzIjFHhjGdYllrTBY
    KyeaeZGJBaHyCfemcu1DZGM0ttfjsFEtAx5b+KNO9uDmuMZ3dEvjjU83esYk8UGX
    qnsb4+cO0mBxa7M9kw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIID3TCCAsWgAwIBAgIJAJ45pK5yokDCMA0GCSqGSIb3DQEBCwUAMFgxDDAKBgNV
    BAoMA2xhYjESMBAGA1UECwwJQ29uanVyIENBMTQwMgYDVQQDDCtkYXAtc2Vydmlj
    ZS1ub2RlLmN5YmVybGFiLnN2Yy5jbHVzdGVyLmxvY2FsMB4XDTIxMTAyMDA5NTQz
    NFoXDTMxMTAxODA5NTQzNFowWDEMMAoGA1UECgwDbGFiMRIwEAYDVQQLDAlDb25q
    dXIgQ0ExNDAyBgNVBAMMK2RhcC1zZXJ2aWNlLW5vZGUuY3liZXJsYWIuc3ZjLmNs
    dXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDbQPas
    OOcIAg3fxHRGOWLQTbqRvoLY+SfjNsr5KSnxT5SbNGj46hx5aC+2MlrWZg52a51R
    MrxDbsgdxtSk/2bl0Cv9zfGcWxISPqXHzf+5LBGcFhWKi8JOrrO75MfJOhCtS2eE
    2pwSTp6fdyTbjmjM9TmMNw9t60iY4nGopuL/fFHi8ogJbgf9EmQVifiG2drJkCUt
    J2UWFclM3eRx4Hu9sLbnXJ9ur9e1PBP6oODK9zz0x88BAIv0tJ6qw4mYAhZFCKc7
    z8Qp1i/NQJT54ddv7no52NfztcNuGszRMl5omcRLkt8WYFF7WklxUldxVq0Cg57q
    BaNcbuJ0CfOPchAhAgMBAAGjgakwgaYwSQYDVR0RBEIwQIIrZGFwLXNlcnZpY2Ut
    bm9kZS5jeWJlcmxhYi5zdmMuY2x1c3Rlci5sb2NhbIIJbG9jYWxob3N0ggZjb25q
    dXIwHQYDVR0OBBYEFJwdqzIWFuKd4oMS3k6oQptjBtzZMB8GA1UdIwQYMBaAFJwd
    qzIWFuKd4oMS3k6oQptjBtzZMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgHmMA0G
    CSqGSIb3DQEBCwUAA4IBAQCodZ3LBu23t49KwgAqkCvSZ4VQcu/T3AtxNuJIVCQT
    77RfUMWR4s5PvkCSQQScWXMdBc82ATPvtBKzwH+ORQdDchJ9BZPZoyZpuDiM49HP
    vua2VkCN5wnS5/5cpTwEDi5uL6jwzR2svKFY8Xvfl0h/SFLsV5MPIyJoeZHpBeO3
    R5GIvdvNxFy0+qKv+p9D6qF4pkHkU4x+iFl1Gt9XwAI558sbi8imzijH5eYSIS4o
    i92I0BvXYRIdAF3gDkc2pphP4mVW6n9kDiq7hjt0OObDFhx4j/5Psq4x7YfFkrHK
    qmj+r87iqlbF8vpeK2BGfC46LjjO0bJhGAo2zk7do61G
    -----END CERTIFICATE-----
  CONJUR_FOLLOWER_CERTIFICATE: |
    -----BEGIN CERTIFICATE-----
    MIIDmTCCAoGgAwIBAgIVAPWJGXeq9H9m0gyd4YlXoSHJP1qnMA0GCSqGSIb3DQEB
    CwUAMFgxDDAKBgNVBAoMA2xhYjESMBAGA1UECwwJQ29uanVyIENBMTQwMgYDVQQD
    DCtkYXAtc2VydmljZS1ub2RlLmN5YmVybGFiLnN2Yy5jbHVzdGVyLmxvY2FsMB4X
    DTIxMTAyMDA5NTQ0MVoXDTMxMTAxODA5NTQ0MVowNjE0MDIGA1UEAwwrZGFwLXNl
    cnZpY2Utbm9kZS5jeWJlcmxhYi5zdmMuY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBAMrvwBCeuB/79O1tm7H678vhP2MtZAo/jLd6
    StVlzFxYQcyGEfSzqX+s6R+7e85hKdSyrPjuLc+c7IDv/RzrEwVVx1fClcZZlMR6
    xY3BX35UDaQpT9bDiAIRgCCBC0571U+u6vGiM0aaOdltEqIUHQfuMje1XM4b1KTv
    bT89iqnqBx9q4l5no69E2a5Opqqb3eRRr+Jrv6Zdt0e8JVXeVIBVGUWkpoftX1YU
    KrA0H0GNQ5qbAZjEbif92UfBETvi6kejTuqYnQlvlsnEIepZ5OUIi67DwOjeLKsD
    rsuhSgq4HAQdJFjBEt0OtJcYYhKLWvYSccfMvuVEN2/t7PrGC30CAwEAAaN8MHow
    DgYDVR0PAQH/BAQDAgWgMB0GA1UdDgQWBBTaOaPuXmtLDTJVv++VYBiQr9gHCTBJ
    BgNVHREEQjBAgitkYXAtc2VydmljZS1ub2RlLmN5YmVybGFiLnN2Yy5jbHVzdGVy
    LmxvY2Fsgglsb2NhbGhvc3SCBmNvbmp1cjANBgkqhkiG9w0BAQsFAAOCAQEA1vl7
    xE+UNiEcN+KuwOP0E120oQ2d22/BS/DE1smjFEqU+JhMN1bsBWRbi8Y+FhbCpkUr
    pqCr7FUW9HB04Sa0Yb/wyoG8F6EcUdPHInXiIv6nH6tiWER5zRVmVn4Ra86vLaA9
    58sBaPowWcRQRGy2FWNvDNiWmI1Z7UBxaL8lV35yKxzye8zbK+TQxtkONv/aNpUI
    Jz/Wg8HXcT3fegyAdKKTUBY1AVs6nsAEBNj10hyB2bj4+xNtzIjFHhjGdYllrTBY
    KyeaeZGJBaHyCfemcu1DZGM0ttfjsFEtAx5b+KNO9uDmuMZ3dEvjjU83esYk8UGX
    qnsb4+cO0mBxa7M9kw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIID3TCCAsWgAwIBAgIJAJ45pK5yokDCMA0GCSqGSIb3DQEBCwUAMFgxDDAKBgNV
    BAoMA2xhYjESMBAGA1UECwwJQ29uanVyIENBMTQwMgYDVQQDDCtkYXAtc2Vydmlj
    ZS1ub2RlLmN5YmVybGFiLnN2Yy5jbHVzdGVyLmxvY2FsMB4XDTIxMTAyMDA5NTQz
    NFoXDTMxMTAxODA5NTQzNFowWDEMMAoGA1UECgwDbGFiMRIwEAYDVQQLDAlDb25q
    dXIgQ0ExNDAyBgNVBAMMK2RhcC1zZXJ2aWNlLW5vZGUuY3liZXJsYWIuc3ZjLmNs
    dXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDbQPas
    OOcIAg3fxHRGOWLQTbqRvoLY+SfjNsr5KSnxT5SbNGj46hx5aC+2MlrWZg52a51R
    MrxDbsgdxtSk/2bl0Cv9zfGcWxISPqXHzf+5LBGcFhWKi8JOrrO75MfJOhCtS2eE
    2pwSTp6fdyTbjmjM9TmMNw9t60iY4nGopuL/fFHi8ogJbgf9EmQVifiG2drJkCUt
    J2UWFclM3eRx4Hu9sLbnXJ9ur9e1PBP6oODK9zz0x88BAIv0tJ6qw4mYAhZFCKc7
    z8Qp1i/NQJT54ddv7no52NfztcNuGszRMl5omcRLkt8WYFF7WklxUldxVq0Cg57q
    BaNcbuJ0CfOPchAhAgMBAAGjgakwgaYwSQYDVR0RBEIwQIIrZGFwLXNlcnZpY2Ut
    bm9kZS5jeWJlcmxhYi5zdmMuY2x1c3Rlci5sb2NhbIIJbG9jYWxob3N0ggZjb25q
    dXIwHQYDVR0OBBYEFJwdqzIWFuKd4oMS3k6oQptjBtzZMB8GA1UdIwQYMBaAFJwd
    qzIWFuKd4oMS3k6oQptjBtzZMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgHmMA0G
    CSqGSIb3DQEBCwUAA4IBAQCodZ3LBu23t49KwgAqkCvSZ4VQcu/T3AtxNuJIVCQT
    77RfUMWR4s5PvkCSQQScWXMdBc82ATPvtBKzwH+ORQdDchJ9BZPZoyZpuDiM49HP
    vua2VkCN5wnS5/5cpTwEDi5uL6jwzR2svKFY8Xvfl0h/SFLsV5MPIyJoeZHpBeO3
    R5GIvdvNxFy0+qKv+p9D6qF4pkHkU4x+iFl1Gt9XwAI558sbi8imzijH5eYSIS4o
    i92I0BvXYRIdAF3gDkc2pphP4mVW6n9kDiq7hjt0OObDFhx4j/5Psq4x7YfFkrHK
    qmj+r87iqlbF8vpeK2BGfC46LjjO0bJhGAo2zk7do61G
    -----END CERTIFICATE-----
