---
# Define project namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ APP_NAMESPACE_NAME }}
  labels:
    name: {{ APP_NAMESPACE_NAME }}

---
# Grant the authentication service access to pods in {{ APP_NAMESPACE_NAME }} namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dap-authn-service
  namespace: {{ APP_NAMESPACE_NAME }}
subjects:
- kind: ServiceAccount
  name: dap-authn-service
  namespace: {{ CYBERARK_NAMESPACE_NAME }}
roleRef:
  kind: ClusterRole
  name: dap-authn-role
  apiGroup: rbac.authorization.k8s.io

---
# Grant namespace admin privileges to {{ APP_NAMESPACE_ADMIN }} user & labadmin SA
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
  namespace: {{ APP_NAMESPACE_NAME }}
subjects:
- kind: User
  name: {{ APP_NAMESPACE_ADMIN }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
# Grant {{ APP_NAMESPACE_ADMIN }} user & labadmin SA read-only access to the DAP config map
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dap-cm-access-user{{ APP_NUM }}
roleRef:
  kind: ClusterRole
  name: dap-cm-access-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: {{ APP_NAMESPACE_ADMIN }}

---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: secrets-access
# rules:
#   - apiGroups: [""]
#     resources: ["secrets"]
#     verbs: [ "get", "update" ]
