# Holds DAP config info for apps in all namespaces
# Access is gained via rolebinding to a clusterrole
# Master and Follower certs are appended after template values instantiated.
apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-dap-config
data:
  CONJUR_ACCOUNT: {{ CONJUR_ACCOUNT }}
  CONJUR_MASTER_HOST_NAME: {{ CONJUR_MASTER_HOSTNAME }}
  CONJUR_MASTER_URL: https://{{ CONJUR_MASTER_HOSTNAME }}
  CLUSTER_AUTHN_ID: {{ CLUSTER_AUTHN_ID }}
  CONJUR_VERSION: "5"
  CONJUR_APPLIANCE_URL: https://conjur-oss.{{ CYBERARK_NAMESPACE_NAME }}.svc.cluster.local
  CONJUR_AUTHN_URL: https://conjur-oss.{{ CYBERARK_NAMESPACE_NAME }}.svc.cluster.local/api/authn-jwt/{{ CLUSTER_AUTHN_ID }}
  CONJUR_AUTHN_TOKEN_FILE: /run/conjur/access-token
